# Generated by Django 6.0.2 on 2026-03-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0003_coursecategory_coursebundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bootcamp Category',
                'verbose_name_plural': 'Bootcamp Categories',
            },
        ),
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_discount', models.BooleanField(default=False)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='bootcamp_thumbnails/')),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bootcamps', to='webashaApp.bootcampcategory')),
            ],
        ),
    ]
