# Generated by Django 6.0.2 on 2026-03-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0004_bootcampcategory_bootcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='classes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='modules_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
