# Generated by Django 6.0.2 on 2026-03-02 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0005_bootcamp_classes_count_bootcamp_modules_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_bootcamps', to=settings.AUTH_USER_MODEL),
        ),
    ]
