# Generated by Django 6.0.2 on 2026-03-02 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0006_bootcamp_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='Stripe', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='webashaApp.bootcamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bootcamp Purchase',
                'verbose_name_plural': 'Bootcamp Purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
