# Generated by Django 6.0.2 on 2026-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0009_ebookcategory_ebook_ebookpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='edition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ebook',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebook',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebook',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='ebook',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='ebook_previews/'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
