# Generated by Django 6.0.2 on 2026-03-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0015_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='support_tickets/'),
        ),
    ]
