# Generated by Django 6.0.2 on 2026-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0018_instructor_testimonial_course_rating_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
