# Generated by Django 6.0.2 on 2026-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0019_testimonial_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='e.g. related_courses', max_length=100, unique=True)),
                ('badge', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(help_text='Supports HTML for custom bolding', max_length=255)),
                ('highlight_text', models.CharField(blank=True, help_text='Text to be rendered in red', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
