# Generated by Django 6.0.2 on 2026-03-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0020_homesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='button_text',
            field=models.CharField(default='Explore More', max_length=255),
        ),
        migrations.AddField(
            model_name='homesection',
            name='curated_courses',
            field=models.ManyToManyField(blank=True, related_name='section_courses', to='webashaApp.course'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='view_all_link',
            field=models.CharField(default='/all-courses', max_length=255),
        ),
        migrations.AddField(
            model_name='homesection',
            name='view_all_text',
            field=models.CharField(default='View All', max_length=255),
        ),
    ]
