# Generated by Django 6.0.2 on 2026-03-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0021_homesection_button_text_homesection_curated_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='review_type',
            field=models.CharField(choices=[('text', 'Text Review'), ('video', 'Video Review')], default='text', max_length=10),
        ),
    ]
