# Generated by Django 6.0.2 on 2026-03-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0022_testimonial_review_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Reference title for the admin', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='video_reviews/')),
                ('video_id', models.CharField(help_text='YouTube Video ID', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
