# Generated by Django 6.0.2 on 2026-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0023_videoreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL of the reviewer', null=True),
        ),
    ]
