# Generated by Django 6.0.2 on 2026-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0026_alter_course_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.CharField(help_text='e.g. 8+ Years of Experience', max_length=255)),
                ('growth_badge', models.CharField(help_text='e.g. 150% Growth', max_length=100)),
                ('description', models.TextField(help_text='Supports HTML formatting like <strong>')),
                ('before_role', models.CharField(max_length=255)),
                ('before_company_name', models.CharField(max_length=255)),
                ('before_company_logo', models.ImageField(upload_to='alumni_companies/')),
                ('after_role', models.CharField(max_length=255)),
                ('after_company_name', models.CharField(max_length=255)),
                ('after_company_logo', models.ImageField(upload_to='alumni_companies/')),
                ('image', models.ImageField(blank=True, help_text='Profile picture of the alumni', null=True, upload_to='alumni_profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alumni Profile',
                'verbose_name_plural': 'Alumni Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
