# Generated by Django 6.0.2 on 2026-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0027_alumniprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamVoucherOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Discounted Certification Exam Voucher', max_length=255)),
                ('image', models.ImageField(upload_to='vouchers/')),
                ('whatsapp_number', models.CharField(default='+91-8010911256', max_length=50)),
                ('whatsapp_message', models.TextField(default='Hello WebAsha, I want Discounted Exam Voucher')),
                ('enroll_link', models.CharField(blank=True, default='#', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
