# Generated by Django 6.0.2 on 2026-03-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0028_examvoucheroffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='e.g. 2026-03-30')),
                ('mode_of_class', models.CharField(default='Online/Classroom', max_length=255)),
                ('batch_form', models.CharField(default='Weekdays', max_length=255)),
                ('time', models.CharField(help_text='e.g. 6:30 PM IST', max_length=255)),
                ('status_text', models.CharField(help_text='e.g. Only 1 Seat Available or Batch Full', max_length=255)),
                ('status_color', models.CharField(choices=[('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow')], default='success', max_length=50)),
                ('max_intake_limit', models.IntegerField(blank=True, help_text='e.g. 10', null=True)),
                ('action_text', models.CharField(default='Enrollment Open →', max_length=255)),
                ('action_color', models.CharField(choices=[('outline-success', 'Green Outline'), ('danger', 'Red Solid')], default='outline-success', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upcoming Batch',
                'verbose_name_plural': 'Upcoming Batches',
                'ordering': ['date'],
            },
        ),
    ]
