# Generated by Django 6.0.2 on 2026-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0029_upcomingbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(help_text='e.g. rhcsa1', max_length=100, unique=True)),
                ('breadcrumb_active', models.CharField(default='RH124 v10 Certification Training', max_length=255)),
                ('heading', models.CharField(default='RH124 v10 Certification Training: Essential Linux System Administration Skills', max_length=255)),
                ('enrolled_count', models.CharField(default='3,850+ Participants Enrolled', max_length=100)),
                ('rating_text', models.CharField(default='4.9/5 (48,765+ Reviews)', max_length=100)),
                ('google_rating', models.CharField(default='4.9/5', max_length=50)),
                ('facebook_rating', models.CharField(default='4.9/5', max_length=50)),
                ('description', models.TextField(help_text='Supports HTML formatting for styling.')),
                ('detail_duration', models.CharField(default='50 Hours (Weekday/Weekend Batches)', max_length=255)),
                ('detail_mode', models.CharField(default='Online & Classroom Training', max_length=255)),
                ('detail_certification', models.CharField(default='Red Hat Certified System Administrator (EX200)', max_length=255)),
                ('detail_institute', models.CharField(default='WebAsha Technologies, Pune', max_length=255)),
                ('detail_includes', models.CharField(default='Hands-on Labs, Official Red Hat Curriculum, Exam Simulations', max_length=255)),
                ('video_thumbnail', models.ImageField(help_text='Image previewing the video', upload_to='course_banners/')),
                ('youtube_video_id', models.CharField(default='ERtp4zua0-s', max_length=100)),
                ('pdf_syllabus_link', models.CharField(blank=True, help_text='Direct link if any, else opens modal', max_length=500, null=True)),
                ('stat_professionals', models.CharField(default='1000+', max_length=50)),
                ('stat_batches', models.CharField(default='8+', max_length=50)),
                ('stat_countries', models.CharField(default='20+', max_length=50)),
                ('stat_clients', models.CharField(default='1000+', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Banner',
                'verbose_name_plural': 'Course Banners',
            },
        ),
    ]
