# Generated by Django 6.0.2 on 2026-03-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0030_coursebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the student or reference label', max_length=255)),
                ('logo_image', models.ImageField(help_text='Circular profile image or logo in the slider', upload_to='student_logos/')),
                ('phone_image', models.ImageField(help_text='The large phone screenshot showing the feedback', upload_to='student_phones/')),
                ('order', models.IntegerField(default=0, help_text='Controls the order in the slider (lowest first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Screenshot',
                'verbose_name_plural': 'Student Screenshots',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
