# Generated by Django 6.0.2 on 2026-03-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0031_studentscreenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, help_text='e.g. RH124v10', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='menu_icon',
            field=models.ImageField(blank=True, null=True, upload_to='course_menu_icons/'),
        ),
        migrations.AddField(
            model_name='course',
            name='menu_label',
            field=models.CharField(choices=[('none', 'None'), ('best_seller', 'Best Seller'), ('trending', 'Trending'), ('new', 'New')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in the mega menu (lowest first)'),
        ),
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.IntegerField(default=0, help_text='Order in the mega menu (lowest first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='webashaApp.coursecategory')),
            ],
            options={
                'verbose_name': 'Course Subcategory',
                'verbose_name_plural': 'Course Subcategories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='webashaApp.coursesubcategory'),
        ),
    ]
