# Generated by Django 6.0.2 on 2026-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0032_alter_coursecategory_options_course_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome class for the mega menu, e.g. fa-solid fa-cloud', max_length=100),
        ),
    ]
