# Generated by Django 6.0.2 on 2026-03-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0033_coursecategory_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='career_benefits_html',
            field=models.TextField(blank=True, help_text='HTML content for Career Benefits'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_info_html',
            field=models.TextField(blank=True, help_text='HTML content for Exam Information & Passing Criteria'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='overview_html',
            field=models.TextField(blank=True, help_text='HTML content for the Course Overview section'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='salary_html',
            field=models.TextField(blank=True, help_text='HTML content for Salary & Job Roles'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='why_choose_us_html',
            field=models.TextField(blank=True, help_text='HTML content for Why Choose Us'),
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(help_text='HTML supported')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='webashaApp.coursebanner')),
            ],
            options={
                'verbose_name': 'Course FAQ',
                'verbose_name_plural': 'Course FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(help_text='e.g. 1. Get Started with Red Hat Enterprise Linux', max_length=255)),
                ('description', models.TextField(blank=True, help_text='HTML supported content for this module')),
                ('order', models.IntegerField(default=0, help_text='Ordering of the module in the accordion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_modules', to='webashaApp.coursebanner')),
            ],
            options={
                'verbose_name': 'Course Syllabus Module',
                'verbose_name_plural': 'Course Syllabus Modules',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
