# Generated by Django 6.0.2 on 2026-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0036_alter_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='Paste full YouTube video URL (e.g. https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coursebanner',
            name='youtube_video_id',
            field=models.CharField(default='ERtp4zua0-s', help_text='Or enter YouTube Video ID directly', max_length=100),
        ),
    ]
