# Generated by Django 6.0.2 on 2026-03-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0037_coursebanner_youtube_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='voucher_offer',
            field=models.ForeignKey(blank=True, help_text='Select a specific Exam Voucher Offer for this page. If empty, uses default active offer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_banners', to='webashaApp.examvoucheroffer'),
        ),
    ]
