# Generated by Django 6.0.2 on 2026-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0038_coursebanner_voucher_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title or alt text', max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('category', models.CharField(blank=True, help_text='E.g., Event, Classroom, Lab (Optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
