# Generated by Django 6.0.2 on 2026-04-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0039_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingbatch',
            name='course_banner',
            field=models.ForeignKey(blank=True, help_text='Select the course page this batch belongs to. If empty, it may appear globally.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_batches', to='webashaApp.coursebanner'),
        ),
    ]
