# Generated by Django 6.0.2 on 2026-04-01 09:14

import webashaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0040_upcomingbatch_course_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=webashaApp.models.generate_cert_id, help_text='Unique Certificate ID, used by students to lookup their certificate.', max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('total_lectures', models.CharField(blank=True, help_text='e.g. 50 Hours or 40 Lectures', max_length=100)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Certificate',
                'verbose_name_plural': 'Student Certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
