# Generated by Django 6.0.2 on 2026-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0042_enquiry_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='course_of_interest',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='course_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
