# Generated by Django 6.0.2 on 2026-04-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0043_delete_enrollment_remove_enquiry_course_of_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(help_text='Company Logo', upload_to='hiring_partners/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hiring Partner',
                'verbose_name_plural': 'Hiring Partners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('package', models.CharField(help_text='e.g. 8.5', max_length=50)),
                ('month_year', models.CharField(help_text='e.g. Apr 2024', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Controls the display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Placed Student',
                'verbose_name_plural': 'Placed Students',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_placements', models.CharField(default='350+', max_length=50)),
                ('average_package', models.CharField(default='8.9 LPA', max_length=50)),
                ('hiring_partners', models.CharField(default='120+', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Placement Stat',
                'verbose_name_plural': 'Placement Stats',
            },
        ),
    ]
