# Generated by Django 6.0.2 on 2026-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0044_hiringpartner_placedstudent_placementstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneRelatedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='related_courses/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short decription to display under the title.', null=True)),
                ('student_count', models.CharField(default='1,000+', max_length=100)),
                ('rating', models.CharField(default='4.8', max_length=50)),
                ('explore_link', models.CharField(default='/all-courses', help_text='The URL that the explore button pushes.', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Standalone Related Course',
                'verbose_name_plural': 'Standalone Related Courses',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
