# Generated by Django 6.0.2 on 2026-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0045_standalonerelatedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exam Name (e.g. Red Hat Certified System Administrator)', max_length=255)),
                ('exam_code', models.CharField(help_text='Exam Code (e.g. EX200)', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the exam')),
                ('price', models.CharField(blank=True, help_text='e.g. 15,000 + GST / $200', max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
