# Generated by Django 6.0.2 on 2026-04-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0046_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(help_text='e.g. EX200', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload exam image if any', null=True, upload_to='exams/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 400.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text='e.g. Red Hat Certified System Administrator', max_length=200),
        ),
    ]
