# Generated by Django 6.0.2 on 2026-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0047_alter_exam_options_exam_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='audience_html',
            field=models.TextField(blank=True, help_text='Audience for This Exam section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='bundle_includes',
            field=models.CharField(default='10-12 Questions & Answers', help_text='e.g. 10-12 Questions & Answers', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='career_opportunities_html',
            field=models.TextField(blank=True, help_text='Career Opportunities section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='certification_value_html',
            field=models.TextField(blank=True, help_text='Certification Value section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='free_updates',
            field=models.CharField(default='90 days', help_text='e.g. 90 days', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='mock_test_count',
            field=models.CharField(default='5-10', help_text='e.g. 5-10', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='objectives_html',
            field=models.TextField(blank=True, help_text='Detailed Exam Objectives section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='overview_html',
            field=models.TextField(blank=True, help_text='General Overview / About the Exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='preparation_mode',
            field=models.CharField(default='Classroom / Online', help_text='e.g. Classroom / Online', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='prerequisites_html',
            field=models.TextField(blank=True, help_text='Prerequisites for This Exam section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='stat_average_score',
            field=models.CharField(default='94%', help_text='e.g. 94%', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='stat_customers_passed',
            field=models.CharField(default='13+', help_text='e.g. 13+', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='stat_similar_questions',
            field=models.CharField(default='92%', help_text='e.g. 92%', max_length=50),
        ),
    ]
