# Generated by Django 6.0.2 on 2026-04-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0048_exam_audience_html_exam_bundle_includes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='box_image',
            field=models.ImageField(blank=True, help_text='The 3D Mock Test / Q&A Box Image', null=True, upload_to='exams/boxes/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='certified_candidates_html',
            field=models.TextField(blank=True, help_text='HTML for Our Certified Candidates slider/images'),
        ),
        migrations.AddField(
            model_name='exam',
            name='eligibility',
            field=models.CharField(default='None', help_text='e.g. None', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_duration',
            field=models.CharField(default='180 Minutes', help_text='e.g. 180 Minutes', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_fee',
            field=models.CharField(default='Varies country to country', help_text='e.g. Varies country to country (20000 + 18% GST for India)', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_format_table',
            field=models.CharField(default='Lab based', help_text='e.g. Lab based', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_languages',
            field=models.CharField(default='English', help_text='e.g. English, Japanese, Korean', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='last_update_date',
            field=models.CharField(default='Apr 08, 2026', help_text='e.g. Apr 08, 2026', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='number_of_questions',
            field=models.CharField(default='10-12', help_text='e.g. 10-12', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='The strike-through price, e.g. 500.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.CharField(default='210 out of 300', help_text='e.g. 210 out of 300', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='subtitle_html',
            field=models.TextField(blank=True, help_text='e.g. Join Our Exam Preparation Class (Bootcamp) | Reviews: 4.9'),
        ),
        migrations.AddField(
            model_name='exam',
            name='validity',
            field=models.CharField(default='3 years', help_text='e.g. 3 years', max_length=100),
        ),
    ]
