# Generated by Django 6.0.2 on 2026-04-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0049_exam_box_image_exam_certified_candidates_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subtitle_html',
        ),
        migrations.AddField(
            model_name='exam',
            name='bootcamp_title',
            field=models.CharField(blank=True, default='Exam Preparation Class (Bootcamp)', help_text='e.g. Exam Preparation Class (Bootcamp)', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='review_count',
            field=models.CharField(blank=True, default='8092', help_text='e.g. 8092', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='review_score',
            field=models.CharField(blank=True, default='4.9', help_text='e.g. 4.9', max_length=10),
        ),
    ]
