# Generated by Django 6.0.2 on 2026-04-17 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0050_remove_exam_subtitle_html_exam_bootcamp_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='certified_candidates_html',
        ),
        migrations.CreateModel(
            name='ExamCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload certificate image', upload_to='exams/certificates/')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='webashaApp.exam')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
