# Generated by Django 6.0.2 on 2026-04-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0051_remove_exam_certified_candidates_html_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order of appearance')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='webashaApp.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamPartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company/partner', max_length=255)),
                ('logo_type', models.CharField(choices=[('learner', 'Our Learners Work At'), ('trusted', 'Trusted By The Best')], default='learner', max_length=20)),
                ('icon_class', models.CharField(blank=True, help_text='e.g. fa-brands fa-microsoft', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Upload image OR use icon_class', null=True, upload_to='exams/partners/')),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_logos', to='webashaApp.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamRelatedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Red Hat OpenStack Administration I EX110', max_length=255)),
                ('bundle_includes', models.CharField(default='597 Questions & Answers', help_text='e.g. 597 Questions & Answers', max_length=255)),
                ('last_update_date', models.CharField(default='Apr 10, 2026', max_length=100)),
                ('price_original', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('price_discounted', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('explore_link', models.CharField(default='/exams', help_text='URL to navigate to', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_courses', to='webashaApp.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='Student', max_length=255)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, help_text='Reviewer profile image', null=True, upload_to='exams/reviews/')),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webashaApp.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
