# Generated by Django 6.0.2 on 2026-04-20 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0052_examfaq_exampartnerlogo_examrelatedcourse_examreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='offer_box_button_text',
            field=models.CharField(blank=True, help_text='e.g. Enroll Here', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='offer_box_button_url',
            field=models.CharField(blank=True, help_text='e.g. /contact or an external link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='offer_box_subtitle',
            field=models.CharField(blank=True, help_text='e.g. Buy 1 Get 1 Exam Voucher', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='offer_box_title',
            field=models.CharField(blank=True, help_text='e.g. Free Red Hat certification exam offer', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ExamAdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('danger', 'Red Theme'), ('dark', 'Dark Theme'), ('primary', 'Blue Theme')], default='danger', max_length=20)),
                ('icon_class', models.CharField(blank=True, help_text='e.g. fa-linux or fa-redhat', max_length=100)),
                ('title', models.CharField(help_text='e.g. Linux', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Training & Certification', max_length=255)),
                ('button_text', models.CharField(default='JOIN NOW', max_length=100)),
                ('button_url', models.CharField(default='/exams', max_length=255)),
                ('contact_email', models.CharField(default='training.webasha@gmail.com', max_length=255)),
                ('contact_phone', models.CharField(default='+918485847920', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_banners', to='webashaApp.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamSidebarCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload 400x250 slider image', upload_to='exams/sidebar/')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_carousels', to='webashaApp.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamWhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g. 100% Latest Exam Questions', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us', to='webashaApp.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
