# Generated by Django 6.0.2 on 2026-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0053_exam_offer_box_button_text_exam_offer_box_button_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='benefits_html',
            field=models.TextField(blank=True, help_text='Benefits of Certification section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='conclusion_html',
            field=models.TextField(blank=True, help_text='Conclusion / How to Pass section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='future_html',
            field=models.TextField(blank=True, help_text='Future / Impact section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.CharField(default='Dubai, UAE', help_text='Location for headers (e.g. Dubai, UAE)', max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='audience_html',
            field=models.TextField(blank=True, help_text='Audience / Bootcamp section'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='career_opportunities_html',
            field=models.TextField(blank=True, help_text='Cost / Career section'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='certification_value_html',
            field=models.TextField(blank=True, help_text='What is Certification section'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='objectives_html',
            field=models.TextField(blank=True, help_text='Passing Criteria section'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='prerequisites_html',
            field=models.TextField(blank=True, help_text='Prerequisites / Syllabus section'),
        ),
    ]
