# Generated by Django 6.0.2 on 2026-04-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0055_custompage'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreview',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Perfect Exam Blueprint', max_length=255),
        ),
    ]
