# Generated by Django 6.0.2 on 2026-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0056_examreview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Top banner background image', null=True, upload_to='pages/banners/'),
        ),
        migrations.AddField(
            model_name='custompage',
            name='banner_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle under banner title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custompage',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Large title over banner', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custompage',
            name='cta_link',
            field=models.CharField(blank=True, help_text='Button URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='custompage',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Button text (e.g. Enroll Now)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custompage',
            name='show_sidebar',
            field=models.BooleanField(default=True, help_text='Show the right-side informational sidebar?'),
        ),
    ]
