# Generated by Django 6.0.2 on 2026-04-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0057_custompage_banner_image_custompage_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
