# Generated by Django 6.0.2 on 2026-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0058_contact_is_read_enquiry_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Live Chat Inquiry',
                'verbose_name_plural': 'Live Chat Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
