# Generated by Django 6.0.2 on 2026-05-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0059_livechatinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select the subcategory this banner belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_banners', to='webashaApp.coursesubcategory'),
        ),
    ]
