# Generated by Django 6.0.2 on 2026-05-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0060_coursebanner_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='call_number',
            field=models.CharField(blank=True, default='+91 848584 7920', max_length=50),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_code',
            field=models.CharField(blank=True, default='EX200', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_duration',
            field=models.CharField(blank=True, default='180 Minutes', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_eligibility',
            field=models.CharField(blank=True, default='None, RH124/RH134 recommended', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_fee',
            field=models.CharField(blank=True, default='Varies (approx ₹20,000 in India)', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_format',
            field=models.CharField(blank=True, default='Hands-On Lab', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_heading_prefix',
            field=models.CharField(blank=True, default='RHCSA Exam', help_text='e.g. RHCSA Exam', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_languages',
            field=models.CharField(blank=True, default='English', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_mode',
            field=models.CharField(blank=True, default='In-Person/Remote Proctor', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_name',
            field=models.CharField(blank=True, default='Red Hat Certified System Administrator (RHCSA)', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_passing_score',
            field=models.CharField(blank=True, default='210 out of 300', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_questions',
            field=models.CharField(blank=True, default='Performance-based tasks', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='exam_detail_validity',
            field=models.CharField(blank=True, default='3 Years', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='passing_criteria_heading',
            field=models.CharField(blank=True, default='Passing Criteria for RHCSA Exam', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='passing_criteria_text',
            field=models.TextField(blank=True, default='To achieve RHCSA certification, score 210/300 on the EX200 hands-on exam (180 min).'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='syllabus_heading_bottom',
            field=models.CharField(blank=True, default='RH124 v10 Certification Training: Essential Linux System Administration Skills Curriculum', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='syllabus_heading_top',
            field=models.CharField(blank=True, default='RH124 v10 Certification Training', help_text='e.g. RH124 v10 Certification Training', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='whatsapp_link',
            field=models.URLField(blank=True, default='https://wa.me/918485847920', max_length=500),
        ),
        migrations.CreateModel(
            name='CourseBannerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, help_text='Candidate Name', max_length=255)),
                ('image', models.ImageField(help_text='Upload certificate image', upload_to='course_banners/certificates/')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='webashaApp.coursebanner')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
