# Generated by Django 6.0.2 on 2026-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0061_coursebanner_call_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='partner_image',
            field=models.ImageField(blank=True, help_text='Upload partner logo (e.g. Red Hat, Cisco)', null=True, upload_to='course_banners/partners/'),
        ),
    ]
