# Generated by Django 6.0.2 on 2026-05-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0062_coursebanner_partner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='show_partner_logo',
            field=models.BooleanField(default=True, help_text='Toggle to show/hide the Accredited By section at the top of the course page', verbose_name='Show Partner Logo/Accreditation Section'),
        ),
        migrations.AlterField(
            model_name='coursebanner',
            name='detail_certification',
            field=models.CharField(blank=True, default='Red Hat Certified System Administrator (EX200)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursebanner',
            name='detail_duration',
            field=models.CharField(blank=True, default='50 Hours (Weekday/Weekend Batches)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursebanner',
            name='detail_includes',
            field=models.CharField(blank=True, default='Hands-on Labs, Official Red Hat Curriculum, Exam Simulations', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursebanner',
            name='detail_institute',
            field=models.CharField(blank=True, default='WebAsha Technologies, Pune', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursebanner',
            name='detail_mode',
            field=models.CharField(blank=True, default='Online & Classroom Training', max_length=255, null=True),
        ),
    ]
