# Generated by Django 6.0.2 on 2026-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0063_coursebanner_show_partner_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebanner',
            name='show_partner_logo',
            field=models.BooleanField(default=True, help_text="Toggle visibility of the 'Accredited By' partner logo section"),
        ),
    ]
