# Generated by Django 6.0.2 on 2026-05-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0064_alter_coursebanner_show_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='slider_image_1',
            field=models.ImageField(blank=True, help_text='Upload first slider image', null=True, upload_to='course_banners/sliders/'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='slider_image_2',
            field=models.ImageField(blank=True, help_text='Upload second slider image', null=True, upload_to='course_banners/sliders/'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='training_track_image',
            field=models.ImageField(blank=True, help_text='Upload course training track image (e.g. certification path diagram)', null=True, upload_to='course_banners/tracks/'),
        ),
    ]
