# Generated by Django 6.0.2 on 2026-05-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0065_coursebanner_slider_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='instructor_description',
            field=models.TextField(blank=True, help_text='Subheading description text under trainer heading', null=True),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='instructor_heading_top',
            field=models.CharField(blank=True, default='Meet Our Expert Trainers', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='instructor_html',
            field=models.TextField(blank=True, help_text='List of bullet points or custom description of trainers', null=True),
        ),
    ]
