# Generated by Django 6.0.2 on 2026-05-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0066_coursebanner_instructor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='description',
            field=models.TextField(help_text='Supports HTML formatting. Maximum 300 characters to keep cards aligned.'),
        ),
    ]
