# Generated by Django 6.0.2 on 2026-05-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0067_alter_alumniprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='key_features_description',
            field=models.TextField(default="Explore the unique benefits of our courses designed for foundational success in Pune's booming IT sector.", help_text='Description for the Key Features section'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='key_features_heading',
            field=models.CharField(default='RH124 v10 Certification Training: Essential Linux System Administration Skills Key Features', help_text='Heading for the Key Features section', max_length=255),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='why_choose_description',
            field=models.TextField(default='At WebAsha Technologies, we deliver career-focused IT training that combines expert mentorship, practical learning, and globally recognized certifications to give you a competitive edge.', help_text='Description for the comparison table section'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='why_choose_heading',
            field=models.CharField(default='Why Choose WebAsha Technologies', help_text='Heading for the comparison table section', max_length=255),
        ),
        migrations.CreateModel(
            name='CourseComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('webasha', models.TextField()),
                ('others', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order in which features are displayed')),
                ('course_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_rows', to='webashaApp.coursebanner')),
            ],
            options={
                'verbose_name': 'Course Comparison Row',
                'verbose_name_plural': 'Course Comparison Rows',
                'ordering': ['order', 'id'],
            },
        ),
    ]
