# Generated by Django 6.0.2 on 2026-05-21 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0068_coursebanner_key_features_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTrackTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('tools_covered', models.TextField(help_text='Tools list (comma separated or plain text)')),
                ('order', models.IntegerField(default=0, help_text='Order in which categories are displayed')),
                ('course_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tools', to='webashaApp.coursebanner')),
            ],
            options={
                'verbose_name': 'Course Track Tool',
                'verbose_name_plural': 'Course Track Tools',
                'ordering': ['order', 'id'],
            },
        ),
    ]
