# Generated by Django 6.0.2 on 2026-05-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0069_coursetracktool'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebanner',
            name='cloud_lab_image',
            field=models.ImageField(blank=True, help_text='Upload custom Cloud Lab image (GIF/PNG/JPG)', null=True, upload_to='course_banners/labs/'),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='cloud_lab_image_url',
            field=models.CharField(blank=True, default='https://i.ibb.co/5X09hRg/lab.gif', help_text='Direct URL of Cloud Lab image/GIF if not uploading a file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coursebanner',
            name='cloud_lab_title',
            field=models.CharField(blank=True, default='Our <span class="red-color">Cloud Lab</span>', help_text='Title for the Cloud Lab section', max_length=255),
        ),
        migrations.CreateModel(
            name='CourseKeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, help_text='Upload key feature icon (e.g. PNG/SVG)', null=True, upload_to='course_banners/features/')),
                ('icon_url', models.CharField(blank=True, help_text='Or enter a direct icon URL / CSS class', max_length=500, null=True)),
                ('label', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('course_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='webashaApp.coursebanner')),
            ],
            options={
                'verbose_name': 'Course Key Feature',
                'verbose_name_plural': 'Course Key Features',
                'ordering': ['order', 'id'],
            },
        ),
    ]
