# Generated by Django 6.0.2 on 2026-05-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0070_coursebanner_cloud_lab_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursebannercertificate',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Training Banner Certificate', 'verbose_name_plural': 'Training Banner Certificates'},
        ),
        migrations.AlterModelOptions(
            name='coursecomparisonrow',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Training Comparison Row', 'verbose_name_plural': 'Training Comparison Rows'},
        ),
        migrations.AlterModelOptions(
            name='coursefaq',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Training FAQ', 'verbose_name_plural': 'Training FAQs'},
        ),
        migrations.AlterModelOptions(
            name='coursekeyfeature',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Training Key Feature', 'verbose_name_plural': 'Training Key Features'},
        ),
        migrations.AlterModelOptions(
            name='coursesyllabus',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Training Syllabus Module', 'verbose_name_plural': 'Training Syllabus Modules'},
        ),
        migrations.AlterModelOptions(
            name='coursetracktool',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Training Track Tool', 'verbose_name_plural': 'Training Track Tools'},
        ),
    ]
