# Generated by Django 6.0.2 on 2026-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webashaApp', '0071_alter_coursebannercertificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomparisonrow',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Why Choose WebAsha', 'verbose_name_plural': 'Why Choose WebAsha'},
        ),
        migrations.AlterField(
            model_name='coursebanner',
            name='why_choose_heading',
            field=models.CharField(default='Why Choose <span class="red-color">WebAsha Technologies</span>', help_text='Heading for the comparison table section', max_length=255),
        ),
    ]
